# Generated by Django 3.2.8 on 2021-11-18 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devotees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('religion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='seva_pics')),
                ('date', models.DateField()),
                ('devotee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotees', to='mygoddess.devotees')),
            ],
        ),
    ]
