# Generated by Django 3.2.8 on 2021-11-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygoddess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seva',
            name='date',
            field=models.CharField(max_length=250),
        ),
    ]
