# Generated by Django 3.2.8 on 2021-11-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygoddess', '0002_alter_seva_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seva',
            name='date',
            field=models.DateField(),
        ),
    ]
