# Generated by Django 3.2.8 on 2021-11-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygoddess', '0003_alter_seva_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotees',
            name='picture',
            field=models.ImageField(default='Picture', upload_to='devotee_pics'),
        ),
        migrations.AddField(
            model_name='devotees',
            name='story',
            field=models.TextField(default='భగవాన్ త్రిషకృష్ణన్ దేవత భక్తుడిని అయినందుకు నేను గర్విస్తున్నాను'),
        ),
    ]
