# Generated by Django 3.2.5 on 2022-05-07 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mygoddess', '0005_remove_seva_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('experience', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
