# Generated by Django 3.2.5 on 2022-05-07 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mygoddess', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slave',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
